#!/bin/sh

# lh_binary_local-hooks(1) - execute local hooks in binary
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Binary_local_hooks ()
{
Echo_message "Begin executing local hooks..."

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

# Checking stage file
Check_stagefile .stage/binary_local-hooks

# Processing local-hooks
if Find_files config/binary_local-hooks/*
then
	for HOOK in config/binary_local-hooks/*
	do
		# Making hook executable
		if [ ! -x "${HOOK}" ]
		then
			chmod +x "${HOOK}"
		fi

		# Executing hook
		./"${HOOK}" || ( Echo_error "${HOOK} failed (exit non-zero). You should check for errors."; exit 1 )
	done

	# Creating stage file
	Create_stagefile .stage/binary_local-hooks
fi
}
