#!/bin/sh

# lh_binary_md5sum(1) - create binary md5sums
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Binary_md5sum ()
{
if [ "${LH_CHECKSUMS}" != "true" ] || [ "${LH_BINARY_IMAGES}" = "virtual-hdd" ]
then
	return
fi

Echo_message "Begin creating binary md5sum.txt..."

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

# Checking stage file
Check_stagefile .stage/binary_md5sum

# Remove old md5sums
if [ -f binary/md5sum.txt ]
then
	rm -f binary/md5sum.txt
fi

# Calculating md5sums
cd binary
find . -type f \! -path './isolinux/isolinux.bin' \! -path './boot/grub/stage2_eltorito' -print0 | sort -z | xargs -0 md5sum > ../md5sum.txt

cat > md5sum.txt << EOF
This file contains the list of md5 checksums of all files on this medium.

You can verify them automatically with the 'integrity-check' boot parameter,
or, manually with: 'md5sum -c md5sum.txt'.


EOF

cat ../md5sum.txt >> md5sum.txt
rm -f ../md5sum.txt

# File list
find . | sed -e 's|^.||g' | grep "^/" | sort > ../binary.list

cd "${OLDPWD}"

# Creating stage file
Create_stagefile .stage/binary_md5sum
}
