#!/bin/sh

# lh_binary_tar(1) - build harddisk binary image
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Binary_tar ()
{
if ! In_list tar "${LH_BINARY_IMAGES}"
then
	return
fi

Echo_message "Begin building binary harddisk image..."

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

# Checking stage file
Check_stagefile .stage/binary_tar

# Remove old binary
rm -f binary.tar.gz

tar cf binary-tar.tar binary
gzip ${GZIP_OPTIONS} binary-tar.tar

# Creating stage file
Create_stagefile .stage/binary_tar
}
