#!/bin/sh

# lh_binary_local-includes(1) - copy files into binary
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Binary_local_includes ()
{
Echo_message "Begin copying binary local includes..."

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

# Checking stage file
Check_stagefile .stage/binary_local-includes

if Find_files config/binary_local-includes/
then
	# Copying includes
	cd config/binary_local-includes
	find . | cpio -dmpu --no-preserve-owner "${OLDPWD}"/binary
	cd "${OLDPWD}"

	# Removing symlinks
	case "${LH_BINARY_IMAGES}" in
		usb*)
			find binary -type l | xargs rm -f
			;;
	esac

	# Creating stage file
	Create_stagefile .stage/binary_local-includes
fi
}
