#!/bin/sh

# lh_binary(1) - build binary images
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Binary ()
{
# Preparing root filesystem
Binary_chroot ${@}

if [ "${LH_CHROOT_BUILD}" = "true" ]
then
	# Configuring chroot
	Chroot_devpts install ${@}
	Chroot_proc install ${@}
	Chroot_selinuxfs install ${@}
	Chroot_sysfs install ${@}
	Chroot_hosts install ${@}
	Chroot_resolv install ${@}
	Chroot_hostname install ${@}
	Chroot_sysv_rc install ${@}
	Chroot_upstart install ${@}
	Chroot_apt install_binary ${@}
	Chroot_sources install ${@}
fi

# Building root filesystem
Binary_rootfs ${@}
Binary_manifest ${@}
Binary_encryption ${@}

# Prepare images
Binary_local_packageslists ${@}
Binary_linux_image ${@}
Binary_debian_installer ${@}
Binary_memtest ${@}
Binary_grub ${@}
Binary_grub2 ${@}
Binary_syslinux ${@}
Binary_yaboot ${@}
Binary_silo ${@}
Binary_disk ${@}
Binary_win32_loader ${@}
Binary_includes ${@}
Binary_local_includes ${@}
Binary_local_hooks ${@}
Binary_md5sum ${@}

if [ "${LH_CHROOT_BUILD}" != "true" ]
then
	Chroot_devpts install ${@}
	Chroot_proc install ${@}
	Chroot_selinuxfs install ${@}
	Chroot_sysfs install ${@}
fi

# Building images
Binary_iso ${@}
Binary_net ${@}
Binary_tar ${@}
Binary_usb ${@}
Binary_virtual_hdd ${@}

if [ "${LH_CHROOT_BUILD}" = "true" ]
then
	# Deconfiguring chroot
	rm -f .stage/chroot_sources
	Chroot_hostname remove ${@}
	Chroot_resolv remove ${@}
	Chroot_hosts remove ${@}
fi

Chroot_apt remove ${@}
Chroot_sysv_rc remove ${@}
Chroot_sysfs remove ${@}
Chroot_upstart remove ${@}
Chroot_selinuxfs remove ${@}
Chroot_proc remove ${@}
Chroot_devpts remove ${@}
}
