#!/bin/sh

# lh_bootstrap_copy(1) - bootstrap by copying the host system
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Bootstrap_copy ()
{
if [ "${LH_BOOTSTRAP}" != "copy" ]
then
	return
fi

# Check architecture
Check_crossarchitecture

Echo_message "Begin bootstrapping system..."

# Ensure that a system is built as root
Testroot

# Checking stage file
Check_stagefile .stage/bootstrap

# Copying host system
mkdir chroot
cd chroot
tar c / --exclude /proc --exclude /sys --exclude "$(dirname ${PWD})" | tar xv
cd ..

# Creating stage file
Create_stagefile .stage/bootstrap
}
