#!/bin/sh

# lh_bootstrap(1) - bootstrap a Debian system
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Bootstrap ()
{
# Bootstrapping system
Bootstrap_cache restore ${@}
Bootstrap_copy ${@}
Bootstrap_cdebootstrap ${@}
Bootstrap_debootstrap ${@}
Bootstrap_cache save ${@}
}
