#!/bin/sh

# lh_chroot_selinuxfs (1) - mount /selinux
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Chroot_selinuxfs ()
{
# Ensure that a system is built as root
Testroot

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

case "${1}" in
	install)
		if [ -e /selinux/enforce ] && [ "$(cat /selinux/enforce)" = "1" ]
		then
			Echo_message "Begin mounting /selinux..."

			# Checking stage file
			Check_stagefile .stage/chroot_selinuxfs

			if [ "${LH_USE_FAKEROOT}" != "true" ]
			then
				# Create mountpoint
				mkdir -p chroot/selinux

				# Mounting /selinux
				${LH_ROOT_COMMAND} mount selinuxfs-live -t selinuxfs chroot/selinux
			else
				rm -rf chroot/selinux
				ln -s /selinux chroot/
			fi

			# Creating stage file
			Create_stagefile .stage/chroot_selinuxfs
		fi
		;;

	remove)
		Echo_message "Begin unmounting /selinux..."

		if [ "${LH_USE_FAKEROOT}" != "true" ]
		then
			# Unmounting /selinux
			#fuser -km chroot/selinux
			if [ -e chroot/selinux/enforce ]
			then
				${LH_ROOT_COMMAND} umount chroot/selinux
			fi
		else
			if [ -e chroot/selinux ]
			then
				rm -rf chroot/selinux
				mkdir -p chroot/selinux
			fi
		fi

		# Removing stage file
		rm -f .stage/chroot_selinux
		;;

	*)
		Usage
		;;
esac
}
