#!/bin/sh

# lh_chroot_sysv-rc(1) - manage /usr/sbin/policy-rc.d
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Chroot_sysv_rc ()
{
# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

case "${1}" in
	install)
		Echo_message "Configuring file /usr/sbin/policy-rc.d"

		# Checking stage file
		Check_stagefile .stage/chroot_sysv-rc

		if [ -f chroot/usr/sbin/policy-rc.d ]
		then
			# Save policy-rc.d file
			mv chroot/usr/sbin/policy-rc.d chroot/usr/sbin/policy-rc.d.orig
		fi

		# Create policy-rc.d file
cat > chroot/usr/sbin/policy-rc.d << EOF
#!/bin/sh
echo "All runlevel operations denied by policy" >&2
exit 101
EOF

		chmod 0755 chroot/usr/sbin/policy-rc.d

		# Creating stage file
		Create_stagefile .stage/chroot_sysv-rc
		;;

	remove)
		Echo_message "Deconfiguring file /usr/sbin/policy-rc.d"

		if [ -f chroot/usr/sbin/policy-rc.d.orig ]
		then
			# Restore policy-rc.d file
			mv chroot/usr/sbin/policy-rc.d.orig chroot/usr/sbin/policy-rc.d
		else
			# Remove policy-rc.d file
			rm -f chroot/usr/sbin/policy-rc.d
		fi

		# Removing stage file
		rm -f .stage/chroot_sysv-rc
		;;

	*)
		Usage
		;;
esac
}
