#!/bin/sh

# lh_chroot_local-packages(1) - queue install of local packages into chroot
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Chroot_local_packages ()
{
Echo_message "Begin queueing installation of local packages..."

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_local-packages

if Find_files chroot/root/local-packages/*.deb
then
	gunzip < chroot/root/local-packages/Packages.gz | awk '/^Package: / { print $2 }' \
		>> chroot/root/chroot_packages

	# Creating stage file
	Create_stagefile .stage/chroot_local-packages
fi
}
