#!/bin/sh

# lh_chroot_local-packageslists(1) - queue install of local packages lists into chroot
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Chroot_local_packageslists ()
{
Echo_message "Begin queueing installation of local packages lists..."

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_local-packageslists

if ls config/chroot_local-packageslists/*.list > /dev/null 2>&1
then
	for LIST in config/chroot_local-packageslists/*.list
	do
		# Generating local package list
		Expand_packagelist "$(basename ${LIST})" "config/chroot_local-packageslists" \
			>> chroot/root/chroot_packages
	done

	# Creating stage file
	Create_stagefile .stage/chroot_local-packageslists
fi
}
