#!/bin/sh

# lh_chroot_local-includes(1) - copy local files into chroot
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Chroot_local_includes ()
{
Echo_message "Begin copying chroot local includes..."

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_local-includes

if Find_files config/chroot_local-includes/
then
	# Copying includes
	cd config/chroot_local-includes
	find . | cpio -dmpu --no-preserve-owner "${OLDPWD}"/chroot
	cd "${OLDPWD}"

	# Creating stage file
	Create_stagefile .stage/chroot_local-includes
fi
}
