#!/bin/sh

# lh_chroot_hooks(1) - execute hooks in chroot
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Chroot_hooks ()
{
Echo_message "Begin executing hooks..."

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_hooks

# Processing hooks
HOOKS="$(echo ${LH_HOOKS} ${LH_PACKAGES_LISTS} ${LH_TASKS} | sed -e 's| |\n|g' | sort -u)"

for HOOK in ${HOOKS}
do
	if [ -f ${LH_BASE:-/usr/share/live-helper}/hooks/"${HOOK}" ]
	then
		# Copying hook
		cp ${LH_BASE:-/usr/share/live-helper}/hooks/"${HOOK}" chroot/root

		# Making hook executable
		if [ ! -x chroot/root/"${HOOK}" ]
		then
			chmod +x chroot/root/"${HOOK}"
		fi

		# Executing hook
		Chroot_target chroot "./root/${HOOK}" || ( Echo_error "${HOOK} failed (exit non-zero). You should check for errors."; exit 1 )

		# Removing hook
		rm -f chroot/root/"${HOOK}"

		# Creating stage file
		Create_stagefile .stage/chroot_hooks
	fi
done
}
