#!/bin/sh

# lh_chroot_local-hooks(1) - execute local hooks in chroot
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Chroot_local_hooks ()
{
Echo_message "Begin executing local hooks..."

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_local-hooks

# Processing local-hooks
if Find_files config/chroot_local-hooks/*
then
	# Restoring cache
	Restore_cache cache/packages_chroot

	for HOOK in config/chroot_local-hooks/*
	do
		# Copying hook
		cp "${HOOK}" chroot/root

		# Making hook executable
		if [ ! -x chroot/root/"$(basename ${HOOK})" ]
		then
			chmod +x chroot/root/"$(basename ${HOOK})"
		fi

		# Executing hook
		Chroot_target chroot "/root/$(basename ${HOOK})" || ( Echo_error "${HOOK} failed (exit non-zero). You should check for errors."; exit 1 )

		# Removing hook
		rm -f chroot/root/"$(basename ${HOOK})"
	done

	# Saving cache
	Save_cache cache/packages_chroot

	# Creating stage file
	Create_stagefile .stage/chroot_local-hooks
fi
}
