#!/bin/sh

# lh_chroot_packageslists(1) - queue install of packages lists into chroot
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Chroot_packageslists ()
{
Echo_message "Begin queueing installation of packages lists..."

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_packageslists

if [ -n "${LH_PACKAGES_LISTS}" ] && [ "${LH_PACKAGES_LISTS}" != "none" ]
then

	for LIST in ${LH_PACKAGES_LISTS}
	do
		# Generating package list
		Expand_packagelist "${LIST}" >> chroot/root/chroot_packages
	done

	# Creating stage file
	Create_stagefile .stage/chroot_packageslists
fi
}
