#!/bin/sh

# lh_chroot_symlinks(1) - convert symlinks
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Chroot_symlinks ()
{
if [ "${LH_SYMLINKS}" != "true" ]
then
	return
fi

Echo_message "Begin converting symlinks..."

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_symlinks

# Checking depends
Check_package chroot/usr/bin/symlinks symlinks

# Installing depends
Install_package

# Converting symlinks
Chroot_target chroot "symlinks -c -r -s /"

# Removing depends
Remove_package

# Creating stage file
Create_stagefile .stage/chroot_symlinks
}
