#!/bin/sh

# lh_chroot_debianchroot(1) - manage /etc/debian_chroot
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Chroot_debianchroot ()
{
# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

case "${1}" in
	install)
		Echo_message "Configuring file /etc/debian_chroot"

		# Checking stage file
		Check_stagefile .stage/chroot_debianchroot

		if [ -f chroot/etc/debian_chroot ]
		then
			# Save chroot file
			mv chroot/etc/debian_chroot chroot/etc/debian_chroot.orig
		fi

		# Create chroot file
		echo "live" > chroot/etc/debian_chroot

		# Creating stage file
		Create_stagefile .stage/chroot_debianchroot
		;;

	remove)
		Echo_message "Deconfiguring file /etc/debian_chroot"

		if [ -f chroot/etc/debian_chroot.orig ]
		then
			# Restore chroot file
			mv chroot/etc/debian_chroot.orig chroot/etc/debian_chroot
		else
			# Remove chroot file
			rm -f chroot/etc/debian_chroot
		fi

		# Removing stage file
		rm -f .stage/chroot_debianchroot
		;;

	*)
		Usage
		;;
esac
}
