#!/bin/sh

# lh_chroot_packages(1) - queue install of packages into chroot
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Chroot_packages ()
{
Echo_message "Begin queueing installation of packages..."

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_packages

if [ -n "${LH_PACKAGES}" ] && [ "${LH_PACKAGES}" != "none" ]
then
	echo ${LH_PACKAGES} >> chroot/root/chroot_packages

	# Creating stage file
	Create_stagefile .stage/chroot_packages
fi
}
