#!/bin/sh

# lh_chroot(1) - customize the Debian system
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Chroot ()
{
# Setup cleanup function
Setup_cleanup

# Configuring chroot
Chroot_cache restore ${@}
Chroot_devpts install ${@}
Chroot_proc install ${@}
Chroot_selinuxfs install ${@}
Chroot_sysfs install ${@}
Chroot_debianchroot install ${@}
Chroot_dpkg install ${@}
Chroot_sysv_rc install ${@}
Chroot_upstart install ${@}
Chroot_hosts install ${@}
Chroot_resolv install ${@}
Chroot_hostname install ${@}
Chroot_apt install ${@}
Chroot_sources install ${@}
Chroot_linux_image install ${@}

# Customizing chroot
Chroot_preseed ${@}
Chroot_local_preseed ${@}
Chroot_tasks ${@}
Chroot_packageslists ${@}
Chroot_local_packageslists ${@}
Chroot_packages ${@}
Chroot_local_packages ${@}
Chroot_install_packages ${@}
Chroot_localization ${@}
Chroot_local_includes ${@}
Chroot_local_patches ${@}
Chroot_sysvinit ${@}
Chroot_local_hooks ${@}
Chroot_hooks ${@}
Chroot_symlinks ${@}
Chroot_hacks ${@}
Chroot_interactive ${@}

# Deconfiguring chroot
Chroot_linux_image remove ${@}
Chroot_sources remove ${@}
Chroot_apt remove ${@}
Chroot_hostname remove ${@}
Chroot_resolv remove ${@}
Chroot_hosts remove ${@}
Chroot_sysv_rc remove ${@}
Chroot_upstart remove ${@}
Chroot_dpkg remove ${@}
Chroot_debianchroot remove ${@}
Chroot_sysfs remove ${@}
Chroot_selinuxfs remove ${@}
Chroot_proc remove ${@}
Chroot_devpts remove ${@}
Chroot_cache save ${@}
}
