#!/bin/sh

# lh_chroot_tasks(1) - install tasks into chroot
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Chroot_tasks ()
{
Echo_message "Begin installing tasks..."

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_tasks

if [ -n "${LH_TASKS}" ] && [ "${LH_TASKS}" != "none" ]
then
	# Restoring cache
	Restore_cache cache/packages_chroot

	# Checking depends
	case "${LH_TASKSEL}" in
		aptitude)
			Check_package chroot/usr/bin/aptitude aptitude
			;;

		tasksel)
			Check_package chroot/usr/bin/tasksel tasksel
			;;
	esac

	# Installing depends
	Install_package

	# Installing tasks
	case "${LH_TASKSEL}" in
		aptitude)
			Chroot_target chroot "aptitude ${APTITUDE_OPTIONS} install ${LH_TASKS}"
			;;

		tasksel)
			for TASK in ${LH_TASKS}
			do
				Chroot_target chroot "tasksel --debconf-apt-progress --logstderr install ${TASK}"
			done
			;;
	esac

	# Removing depends
	Remove_package

	# Saving cache
	Save_cache cache/packages_chroot

	# Creating stage file
	Create_stagefile .stage/chroot_tasks
fi
}
