#!/bin/sh

# lh_chroot_interactive(1) - make build interactive
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Chroot_interactive ()
{
if [ "${LH_INTERACTIVE}" = "false" ]
then
	return
fi

Echo_message "Begin interactive build..."

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_interactive

case "${LH_INTERACTIVE}" in
	true|shell)
		Echo_message "Pausing build: starting interactive shell..."
			Chroot_target chroot "/bin/bash --login"
		;;
		x11)
		Echo_message "Pausing build: starting interactive X11..."
			Chroot_target chroot "startx"
		;;
		xnest)
		Echo_message "Pausing build: starting interactive Xnest..."
			#Chroot_target chroot "" # FIXME
		;;
esac

# Creating stage file
Create_stagefile .stage/chroot_symlinks
}
