#!/bin/sh

# lh_chroot_local-patches(1) - apply local patches against chroot
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Chroot_local_packages ()
{
Echo_message "Begin applying chroot local patches..."

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_local-patches

if Find_files config/chroot_local-patches/
then
	# Restoring cache
	Restore_cache cache/packages_chroot

	# Checking depends
	Check_package chroot/usr/bin/patch patch

	# Installing depends
	Install_package

	for PATCH in config/chroot_local-patches/*
	do
		Echo_message "Applying patch %s..." "${PATCH}"
		Chroot_target chroot "patch -p1" < ${PATCH}
	done

	# Removing depends
	Remove_package

	# Saving cache
	Save_cache cache/packages_chroot

	# Creating stage file
	Create_stagefile .stage/chroot_local-patches
fi
}
