#!/bin/sh

# lh_chroot_cache(1) - cach chroot stage
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Chroot_cache ()
{
Echo_message "Begin caching chroot stage..."

for STAGE in ${LH_CACHE_STAGES}
do
	if [ "${STAGE}" = "chroot" ]
	then
		case "${1}" in
			restore)
				# Checking stage file
				Check_stagefile .stage/chroot_cache.restore

				if [ -d cache/stages_chroot ]
				then
					# Removing old chroot
					rm -rf chroot

					# Restoring old cache
					${LH_ROOT_COMMAND} cp -a cache/stages_chroot chroot

					if [ -n "${LH_ROOT_COMMAND}" ]
					then
						${LH_ROOT_COMMAND} chown -R $(whoami):$(whoami) chroot
					fi

					# Creating stage file
					Create_stagefile .stage/chroot_cache.restore
				fi
				;;

			save)
				# Checking stage file
				Check_stagefile .stage/chroot_cache.save

				rm -rf cache/stages_chroot

				mkdir -p cache

				${LH_ROOT_COMMAND} cp -a chroot cache/stages_chroot

				if [ -n "${LH_ROOT_COMMAND}" ]
				then
					${LH_ROOT_COMMAND} chown -R $(whoami):$(whoami) cache/stages_chroot
				fi

				# Creating stage file
				Create_stagefile .stage/chroot_cache.save
				;;
		esac
	fi
done
}
