#!/bin/sh

# lh_chroot_preseed(1) - use debconf preseeding file
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Chroot_preseed ()
{
Echo_message "Begin executing preseed..."

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

# Checking stage file
Check_stagefile .stage/chroot_preseed

# Processing preseeds
for PRESEED in ${LH_PACKAGES_LISTS} ${LH_TASKS}
do
	if [ -f ${LH_BASE:-/usr/share/live-helper}/preseed/"${PRESEED}" ]
	then
		# Check dependency
		Check_package chroot/usr/bin/debconf-set-selections debconf

		# Install dependency
		Install_package

		# Copying preseed
		cp "${PRESEED}" chroot/root/preseed

		Chroot_target chroot "debconf-set-selections /root/preseed"

		# Removing preseed file
		rm -f chroot/root/preseed

		# Remove dependency
		Remove_package

		# Creating stage file
		Create_stagefile .stage/chroot_preseed
	fi
done
}
