#!/bin/sh

# lh_chroot_upstart(1) - manage /usr/sbin/initctl
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Chroot_upstart ()
{
# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

case "${1}" in
	install)
		Echo_message "Configuring file /usr/sbin/initctl"

		# Checking stage file
		Check_stagefile .stage/chroot_upstart

		if [ -f chroot/usr/sbin/initctl ]
		then
			# Save initctl file
			mv chroot/usr/sbin/initctl chroot/usr/sbin/initctl.orig
		fi

		# Create initctl file
cat > chroot/usr/sbin/initctl << EOF
#!/bin/sh
echo "All runlevel operations denied by policy" >&2
exit 101
EOF

		chmod 0755 chroot/usr/sbin/initctl

		# Creating stage file
		Create_stagefile .stage/chroot_upstart
		;;

	remove)
		Echo_message "Deconfiguring file /usr/sbin/initctl"

		if [ -f chroot/usr/sbin/initctl.orig ]
		then
			# Restore initctl file
			mv chroot/usr/sbin/initctl.orig chroot/usr/sbin/initctl
		else
			# Remove initctl file
			rm -f chroot/usr/sbin/initctl
		fi

		# Removing stage file
		rm -f .stage/chroot_upstart
		;;

	*)
		Usage
		;;
esac
}
