#!/bin/sh

# lh(1) - generic live-helper wrapper
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/live-helper.sh

# Setting static variables
DESCRIPTION="$(Echo 'utility to build Debian Live systems')"
HELP="FIXME"
USAGE="FIXME"

case "${1}" in
	-h|--help)
		if [ -x "$(which man 2>/dev/null)" ]
		then
			man lh
			exit 0
		else
			${0} --usage
			exit 0
		fi
		;;

	""|-u|--usage)
		Usage
		exit 0
		;;

	-v|--version)
		Version
		exit 0
		;;
esac

COMMAND="${1}"
FUNCTION="$(echo ${COMMAND} | cut -b 1 | tr a-z A-Z)$(echo ${COMMAND} | cut -b 2- | sed -e 's|-|_|g')"
shift

# Reading configuration files
Read_conffiles config/all config/common config/bootstrap config/chroot config/binary config/source
Set_defaults

# Checking lock file
Check_lockfile .lock

# Creating lock file
Create_lockfile .lock

# Setup cleanup function
Setup_cleanup

${FUNCTION} ${@}
