#!/bin/sh

# lh_source(1) - build source images
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Source ()
{
Require_stagefile .stage/chroot_install-packages

# Enabling network in chroot
Chroot_hosts install ${@}
Chroot_resolv install ${@}
Chroot_hostname install ${@}
Chroot_sources install ${@}

# Preparing images
Source_debian-live ${@}
Source_debian ${@}
Source_disk ${@}
Source_md5sum ${@}

# Building images
Source_iso ${@}
Source_net ${@}
Source_tar ${@}
Source_usb ${@}
Source_virtual-hdd ${@}

# Deconfiguring chroot
rm -f .stage/chroot_sources
Chroot_hostname remove ${@}
Chroot_resolv remove ${@}
Chroot_hosts remove ${@}
}
