#!/bin/sh

# lh_source_net(1) - build source net image
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Source_net ()
{
if [ "${LH_SOURCE}" != "true" ]
then
	return
fi

if ! In_list net "${LH_SOURCE_IMAGES}"
then
	return
fi

Echo_message "Begin building source netboot image..."

# Requiring stage file
Require_stagefile .stage/config .stage/source_debian

# Checking stage file
Check_stagefile .stage/source_net

# Remove old source
if [ -f source-net.tar.gz ]
then
	rm -f source-net.tar.gz
fi

# Create tarball
tar cf source-net.tar source
gzip ${GZIP_OPTIONS} source-net.tar

# Creating stage file
Create_stagefile .stage/source_net
}
