#!/bin/sh

# lh_source_disk (1) - install disk information into source
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Source_disk ()
{
case "${LH_SOURCE_IMAGES}" in
	iso*)
		;;

	*)
		return
		;;
esac

Echo_message "Begin installing disk information..."

# Requiring stage file
Require_stagefile .stage/config .stage/bootstrap

# Checking stage file
Check_stagefile .stage/source_disk

mkdir -p source/.disk

TITLE="Debian GNU/Linux"
DISTRIBUTION="$(echo ${LH_DISTRIBUTION} | cut -b 1 | tr '[a-z]' '[A-Z]')"
DISTRIBUTION="${DISTRIBUTION}$(echo ${LH_DISTRIBUTION} | cut -b 2-)"
eval VERSION="$`echo RELEASE_${LH_DISTRIBUTION}`"

case "${LH_MODE}" in
	debian)
		STRING="Official Snapshot ${ARCHITECTURE}"
		TRACE="project/trace/ftp-master.debian.org"
		;;

	debian-release)
		STRING="Official ${ARCHITECTURE}"
		TRACE="project/trace/ftp-master.debian.org"
		;;

	ubuntu)
		TITLE="Ubuntu GNU/Linux"
		STRING="Build ${ARCHITECTURE}"
		TRACE=""
		;;

	*)
		STRING="Snapshot ${ARCHITECTURE}"
		TRACE=""
		;;
esac

if [ -n "${TRACE}" ]
then
	echo "$(wget -q ${LH_MIRROR_BOOTSTRAP}/${TRACE} -O - | head -n 1)" \
	> source/.disk/archive_trace
fi

case "${LH_DEBIAN_INSTALLER}" in
	cdrom)
		echo "${TITLE} ${VERSION} \"${DISTRIBUTION}\" - ${STRING} LIVE/CD Source $(date +%Y%m%d-%H:%M)" > source/.disk/info
		;;

	true|netinst)
		echo "${TITLE} ${VERSION} \"${DISTRIBUTION}\" - ${STRING} LIVE/NETINST Source $(date +%Y%m%d-%H:%M)" > source/.disk/info
		;;

	live)
		echo "${TITLE} ${VERSION} \"${DISTRIBUTION}\" - ${STRING} LIVE/INSTALL Source $(date +%Y%m%d-%H:%M)" > source/.disk/info
		;;

	businesscard)
		echo "${TITLE} ${VERSION} \"${DISTRIBUTION}\" - ${STRING} LIVE/BC Source $(date +%Y%m%d-%H:%M)" > source/.disk/info
		;;

	false)
		echo "${TITLE} ${VERSION} \"${DISTRIBUTION}\" - ${STRING} LIVE Source $(date +%Y%m%d-%H:%M)" > source/.disk/info
		;;
esac

# Creating stage file
Create_stagefile .stage/source_disk
}
