#!/bin/sh

# lh_source_iso(1) - build iso source image
# Copyright (C) 2006-2010 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

Source_iso ()
{
if [ "${LH_SOURCE}" != "true" ]
then
	return
fi

case "${LH_SOURCE_IMAGES}" in
	iso*)
		;;

	*)
		return
		;;
esac

Echo_message "Begin building source iso image..."

# Requiring stage file
Require_stagefile .stage/config .stage/source_debian

# Checking stage file
Check_stagefile .stage/source_iso

# Checking depends
Check_package chroot/usr/bin/genisoimage genisoimage

# Installing depends
Install_package

# Remove old iso image
if [ -f source.iso ]
then
	rm -f source.iso
fi

if [ "${_QUIET}" = "true" ]
then
	GENISOIMAGE_OPTIONS="${GENISOIMAGE_OPTIONS} -quiet"
fi

if [ "${_VERBOSE}" = "true" ]
then
	GENISOIMAGE_OPTIONS="${GENISOIMAGE_OPTIONS} -v"
fi

if [ -n "${LH_ISO_APPLICATION}" ] && [ "${LH_ISO_APPLICATION}" != "none" ]
then
	GENISOIMAGE_OPTIONS="${GENISOIMAGE_OPTIONS} -A \"${LH_ISO_APPLICATION}\""
fi

if [ -n "${LH_ISO_PREPARER}" ] && [ "${LH_ISO_PREPARER}" != "none" ]
then
	GENISOIMAGE_OPTIONS="${GENISOIMAGE_OPTIONS} -p \"${LH_ISO_PREPARER}\""
fi

if [ -n "${LH_ISO_PUBLISHER}" ] && [ "${LH_ISO_PUBLISHER}" != "none" ]
then
	GENISOIMAGE_OPTIONS="${GENISOIMAGE_OPTIONS} -publisher \"${LH_ISO_PUBLISHER}\""
fi

if [ -n "${LH_ISO_VOLUME}" ] && [ "${LH_ISO_VOLUME}" != "none" ]
then
	GENISOIMAGE_OPTIONS="${GENISOIMAGE_OPTIONS} -V \"${LH_ISO_VOLUME}\""
fi

# Moving image
mv source chroot

cat >> chroot/source.sh << EOF
genisoimage ${GENISOIMAGE_OPTIONS} -o source.iso -r -J -l -cache-inodes source
EOF

Chroot_target chroot "sh source.sh"

# Move image
mv chroot/source chroot/source.iso ./
rm -f chroot/source.sh

# Removing depends
Remove_package

# Creating stage file
Create_stagefile .stage/source_iso
}
